// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeTable.Models;

namespace TimeTable.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TimeTable.Models.Entities.Assessment", b =>
                {
                    b.Property<int>("AssessmentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssessmentName");

                    b.Property<int>("AssessmentType");

                    b.Property<string>("Description");

                    b.Property<string>("Duration");

                    b.Property<DateTime>("EndTime");

                    b.Property<double?>("FinalWeight");

                    b.Property<double>("Mark");

                    b.Property<int>("ModuleID");

                    b.Property<double?>("PredicateWeight");

                    b.Property<DateTime>("StartTime");

                    b.HasKey("AssessmentID");

                    b.HasIndex("ModuleID");

                    b.ToTable("Assessments");

                    b.HasData(
                        new
                        {
                            AssessmentID = 500,
                            AssessmentName = "Semester Test 1",
                            AssessmentType = 1,
                            Description = " ",
                            Duration = "1Hr",
                            EndTime = new DateTime(2019, 8, 12, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Mark = 50.0,
                            ModuleID = 403,
                            PredicateWeight = 30.0,
                            StartTime = new DateTime(2019, 8, 12, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AssessmentID = 501,
                            AssessmentName = "Semester Test 2",
                            AssessmentType = 1,
                            Description = " ",
                            Duration = "1Hr",
                            EndTime = new DateTime(2019, 10, 12, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Mark = 50.0,
                            ModuleID = 403,
                            PredicateWeight = 30.0,
                            StartTime = new DateTime(2019, 10, 14, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AssessmentID = 502,
                            AssessmentName = "Main Exam 1",
                            AssessmentType = 0,
                            Description = " ",
                            Duration = "3hrs",
                            EndTime = new DateTime(2019, 11, 8, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalWeight = 50.0,
                            Mark = 100.0,
                            ModuleID = 403,
                            StartTime = new DateTime(2019, 11, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AssessmentID = 503,
                            AssessmentName = "Assignment 1",
                            AssessmentType = 2,
                            Description = " ",
                            Duration = "1 month",
                            EndTime = new DateTime(2019, 10, 15, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Mark = 100.0,
                            ModuleID = 403,
                            PredicateWeight = 20.0,
                            StartTime = new DateTime(2019, 9, 15, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AssessmentID = 504,
                            AssessmentName = "Online Quiz 1",
                            AssessmentType = 3,
                            Description = " ",
                            Duration = "5 days",
                            EndTime = new DateTime(2019, 10, 15, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Mark = 30.0,
                            ModuleID = 403,
                            PredicateWeight = 10.0,
                            StartTime = new DateTime(2019, 10, 10, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AssessmentID = 505,
                            AssessmentName = "Assignment 2",
                            AssessmentType = 2,
                            Description = " ",
                            Duration = "5 days",
                            EndTime = new DateTime(2019, 10, 15, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Mark = 30.0,
                            ModuleID = 403,
                            PredicateWeight = 10.0,
                            StartTime = new DateTime(2019, 10, 10, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AssessmentID = 506,
                            AssessmentName = "Semester Test 1",
                            AssessmentType = 1,
                            Description = " ",
                            Duration = "1hr",
                            EndTime = new DateTime(2019, 9, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Mark = 60.0,
                            ModuleID = 401,
                            PredicateWeight = 30.0,
                            StartTime = new DateTime(2019, 9, 25, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AssessmentID = 507,
                            AssessmentName = "Main Exam 1",
                            AssessmentType = 0,
                            Description = " ",
                            Duration = "3hrs",
                            EndTime = new DateTime(2019, 11, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalWeight = 50.0,
                            Mark = 100.0,
                            ModuleID = 401,
                            StartTime = new DateTime(2019, 11, 15, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AssessmentID = 508,
                            AssessmentName = "Assignment 1",
                            AssessmentType = 1,
                            Description = " ",
                            Duration = "7 Days",
                            EndTime = new DateTime(2019, 9, 17, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Mark = 20.0,
                            ModuleID = 401,
                            PredicateWeight = 20.0,
                            StartTime = new DateTime(2019, 9, 10, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AssessmentID = 509,
                            AssessmentName = "Semester Test 2",
                            AssessmentType = 1,
                            Description = " ",
                            Duration = "1hr",
                            EndTime = new DateTime(2019, 11, 2, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Mark = 60.0,
                            ModuleID = 401,
                            PredicateWeight = 30.0,
                            StartTime = new DateTime(2019, 11, 2, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AssessmentID = 510,
                            AssessmentName = "Assignment 2",
                            AssessmentType = 2,
                            Description = " ",
                            Duration = "13 Days",
                            EndTime = new DateTime(2019, 10, 23, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Mark = 100.0,
                            ModuleID = 401,
                            PredicateWeight = 20.0,
                            StartTime = new DateTime(2019, 10, 11, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AssessmentID = 511,
                            AssessmentName = "Semester Test 1",
                            AssessmentType = 1,
                            Description = " ",
                            Duration = "1hr",
                            EndTime = new DateTime(2019, 9, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Mark = 50.0,
                            ModuleID = 402,
                            PredicateWeight = 35.0,
                            StartTime = new DateTime(2019, 9, 20, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AssessmentID = 512,
                            AssessmentName = "Main Exam 1",
                            AssessmentType = 0,
                            Description = " ",
                            Duration = "3hrs",
                            EndTime = new DateTime(2019, 11, 18, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalWeight = 50.0,
                            Mark = 100.0,
                            ModuleID = 402,
                            StartTime = new DateTime(2019, 11, 18, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AssessmentID = 513,
                            AssessmentName = "Assignment 1",
                            AssessmentType = 1,
                            Description = " ",
                            Duration = "7 Days",
                            EndTime = new DateTime(2019, 9, 13, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Mark = 52.0,
                            ModuleID = 402,
                            PredicateWeight = 45.0,
                            StartTime = new DateTime(2019, 9, 6, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AssessmentID = 514,
                            AssessmentName = "Semester Test 2",
                            AssessmentType = 1,
                            Description = " ",
                            Duration = "1hr",
                            EndTime = new DateTime(2019, 11, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Mark = 42.0,
                            ModuleID = 402,
                            PredicateWeight = 50.0,
                            StartTime = new DateTime(2019, 11, 15, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AssessmentID = 515,
                            AssessmentName = "Assignment 2",
                            AssessmentType = 2,
                            Description = " ",
                            Duration = "23 Days",
                            EndTime = new DateTime(2019, 10, 23, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Mark = 70.0,
                            ModuleID = 402,
                            PredicateWeight = 55.0,
                            StartTime = new DateTime(2019, 10, 1, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AssessmentID = 516,
                            AssessmentName = "Semester Test 1",
                            AssessmentType = 1,
                            Description = " ",
                            Duration = "1Hr",
                            EndTime = new DateTime(2019, 8, 11, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Mark = 50.0,
                            ModuleID = 404,
                            PredicateWeight = 30.0,
                            StartTime = new DateTime(2019, 8, 11, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AssessmentID = 517,
                            AssessmentName = "Semester Test 2",
                            AssessmentType = 1,
                            Description = " ",
                            Duration = "1Hr",
                            EndTime = new DateTime(2019, 10, 16, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Mark = 60.0,
                            ModuleID = 404,
                            PredicateWeight = 30.0,
                            StartTime = new DateTime(2019, 10, 16, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AssessmentID = 518,
                            AssessmentName = "Main Exam 1",
                            AssessmentType = 0,
                            Description = " ",
                            Duration = "3hrs",
                            EndTime = new DateTime(2019, 11, 23, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalWeight = 60.0,
                            Mark = 100.0,
                            ModuleID = 404,
                            StartTime = new DateTime(2019, 11, 23, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AssessmentID = 519,
                            AssessmentName = "Assignment 1",
                            AssessmentType = 2,
                            Description = " ",
                            Duration = "15 Days",
                            EndTime = new DateTime(2019, 10, 15, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Mark = 50.0,
                            ModuleID = 404,
                            PredicateWeight = 20.0,
                            StartTime = new DateTime(2019, 9, 1, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AssessmentID = 520,
                            AssessmentName = "Online Quiz 1",
                            AssessmentType = 3,
                            Description = " ",
                            Duration = "7 days",
                            EndTime = new DateTime(2019, 9, 24, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Mark = 40.0,
                            ModuleID = 404,
                            PredicateWeight = 10.0,
                            StartTime = new DateTime(2019, 9, 17, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AssessmentID = 521,
                            AssessmentName = "Assignment 2",
                            AssessmentType = 2,
                            Description = " ",
                            Duration = "5 days",
                            EndTime = new DateTime(2019, 10, 15, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            Mark = 100.0,
                            ModuleID = 404,
                            PredicateWeight = 10.0,
                            StartTime = new DateTime(2019, 10, 10, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TimeTable.Models.Entities.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title");

                    b.HasKey("CourseID");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseID = 201,
                            Title = "BSc. IT"
                        },
                        new
                        {
                            CourseID = 202,
                            Title = "BIS"
                        });
                });

            modelBuilder.Entity("TimeTable.Models.Entities.Lecture", b =>
                {
                    b.Property<int>("LectureID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ModuleID");

                    b.Property<int>("VenueID");

                    b.Property<string>("end_time");

                    b.Property<string>("start_time");

                    b.HasKey("LectureID");

                    b.ToTable("Lecture");

                    b.HasData(
                        new
                        {
                            LectureID = 1,
                            ModuleID = 401,
                            VenueID = 302,
                            end_time = "Thursday,14:00",
                            start_time = "Thursday,13:10"
                        },
                        new
                        {
                            LectureID = 2,
                            ModuleID = 401,
                            VenueID = 302,
                            end_time = "Monday,14:00",
                            start_time = "Monday,13:10"
                        },
                        new
                        {
                            LectureID = 3,
                            ModuleID = 401,
                            VenueID = 301,
                            end_time = "Tuesday,17:00",
                            start_time = "Tuesday,15:10"
                        },
                        new
                        {
                            LectureID = 4,
                            ModuleID = 401,
                            VenueID = 302,
                            end_time = "Wednesday,13:10",
                            start_time = "Wednesday,13:10"
                        },
                        new
                        {
                            LectureID = 5,
                            ModuleID = 402,
                            VenueID = 301,
                            end_time = "Monday,13:00",
                            start_time = "Monday,12:10"
                        },
                        new
                        {
                            LectureID = 6,
                            ModuleID = 402,
                            VenueID = 302,
                            end_time = "Tuesday,18:10",
                            start_time = "Tuesday,15:10"
                        },
                        new
                        {
                            LectureID = 7,
                            ModuleID = 403,
                            VenueID = 303,
                            end_time = "Friday,14:00",
                            start_time = "Friday,13:10"
                        },
                        new
                        {
                            LectureID = 8,
                            ModuleID = 403,
                            VenueID = 301,
                            end_time = "Monday,10:00",
                            start_time = "Monday,09:10"
                        },
                        new
                        {
                            LectureID = 9,
                            ModuleID = 403,
                            VenueID = 303,
                            end_time = "Tuesday,18:00",
                            start_time = "Tuesday,17:10"
                        },
                        new
                        {
                            LectureID = 10,
                            ModuleID = 403,
                            VenueID = 302,
                            end_time = "Wedesday,12:00",
                            start_time = "Wednesday,11:10"
                        },
                        new
                        {
                            LectureID = 11,
                            ModuleID = 404,
                            VenueID = 303,
                            end_time = "Monday,09:00",
                            start_time = "Monday,08:10"
                        },
                        new
                        {
                            LectureID = 12,
                            ModuleID = 404,
                            VenueID = 303,
                            end_time = "Tuesday,10:00",
                            start_time = "Tuesday,08:10"
                        },
                        new
                        {
                            LectureID = 13,
                            ModuleID = 404,
                            VenueID = 303,
                            end_time = "Monday,9:00",
                            start_time = "Monday,08:10"
                        },
                        new
                        {
                            LectureID = 14,
                            ModuleID = 404,
                            VenueID = 303,
                            end_time = "Friday,10:10",
                            start_time = "Friday,08:10"
                        });
                });

            modelBuilder.Entity("TimeTable.Models.Entities.Lecturer", b =>
                {
                    b.Property<int>("LecturerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseID");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("LecturerID");

                    b.ToTable("Lecturers");

                    b.HasData(
                        new
                        {
                            LecturerID = 123456789,
                            FirstName = "Rouxanne",
                            LastName = "Fouche"
                        },
                        new
                        {
                            LecturerID = 135792468,
                            FirstName = "Pieter",
                            LastName = "Bligies"
                        },
                        new
                        {
                            LecturerID = 987654321,
                            FirstName = "Jaco",
                            LastName = "Marais"
                        },
                        new
                        {
                            LecturerID = 148269367,
                            FirstName = "Lizette",
                            LastName = "de Wet"
                        },
                        new
                        {
                            LecturerID = 185473538,
                            FirstName = "Ruan",
                            LastName = "van der Westuizen"
                        },
                        new
                        {
                            LecturerID = 987679543,
                            FirstName = "Franco",
                            LastName = "van der Merwe"
                        },
                        new
                        {
                            LecturerID = 776546879,
                            FirstName = "Khanya",
                            LastName = "Kolo"
                        });
                });

            modelBuilder.Entity("TimeTable.Models.Entities.Mark", b =>
                {
                    b.Property<int>("MarkID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssessmentID");

                    b.Property<int?>("MarkType");

                    b.Property<double>("MarkValue");

                    b.Property<int>("StudentID");

                    b.HasKey("MarkID");

                    b.ToTable("Marks");

                    b.HasData(
                        new
                        {
                            MarkID = 1,
                            AssessmentID = 501,
                            MarkType = 1,
                            MarkValue = 76.0,
                            StudentID = 2017876764
                        },
                        new
                        {
                            MarkID = 2,
                            AssessmentID = 502,
                            MarkType = 1,
                            MarkValue = 63.0,
                            StudentID = 2017876764
                        },
                        new
                        {
                            MarkID = 3,
                            AssessmentID = 503,
                            MarkType = 1,
                            MarkValue = 86.0,
                            StudentID = 2017876764
                        },
                        new
                        {
                            MarkID = 4,
                            AssessmentID = 504,
                            MarkType = 1,
                            MarkValue = 48.0,
                            StudentID = 2017876764
                        },
                        new
                        {
                            MarkID = 5,
                            AssessmentID = 505,
                            MarkType = 1,
                            MarkValue = 94.0,
                            StudentID = 2017876764
                        },
                        new
                        {
                            MarkID = 6,
                            AssessmentID = 506,
                            MarkType = 1,
                            MarkValue = 61.0,
                            StudentID = 2017876764
                        },
                        new
                        {
                            MarkID = 7,
                            AssessmentID = 507,
                            MarkType = 1,
                            MarkValue = 68.0,
                            StudentID = 2017876764
                        },
                        new
                        {
                            MarkID = 8,
                            AssessmentID = 508,
                            MarkType = 1,
                            MarkValue = 60.0,
                            StudentID = 2017876764
                        },
                        new
                        {
                            MarkID = 9,
                            AssessmentID = 509,
                            MarkType = 1,
                            MarkValue = 69.0,
                            StudentID = 2017876764
                        },
                        new
                        {
                            MarkID = 10,
                            AssessmentID = 510,
                            MarkType = 1,
                            MarkValue = 65.0,
                            StudentID = 2017876764
                        },
                        new
                        {
                            MarkID = 11,
                            AssessmentID = 511,
                            MarkType = 1,
                            MarkValue = 64.0,
                            StudentID = 2017876764
                        },
                        new
                        {
                            MarkID = 12,
                            AssessmentID = 512,
                            MarkType = 1,
                            MarkValue = 27.0,
                            StudentID = 2017876764
                        },
                        new
                        {
                            MarkID = 13,
                            AssessmentID = 513,
                            MarkType = 1,
                            MarkValue = 48.0,
                            StudentID = 2017876764
                        },
                        new
                        {
                            MarkID = 14,
                            AssessmentID = 514,
                            MarkType = 1,
                            MarkValue = 99.0,
                            StudentID = 2017876764
                        },
                        new
                        {
                            MarkID = 15,
                            AssessmentID = 515,
                            MarkType = 1,
                            MarkValue = 62.0,
                            StudentID = 2017876764
                        },
                        new
                        {
                            MarkID = 16,
                            AssessmentID = 516,
                            MarkType = 1,
                            MarkValue = 85.0,
                            StudentID = 2017876764
                        },
                        new
                        {
                            MarkID = 17,
                            AssessmentID = 517,
                            MarkType = 1,
                            MarkValue = 61.0,
                            StudentID = 2017876764
                        },
                        new
                        {
                            MarkID = 18,
                            AssessmentID = 518,
                            MarkType = 1,
                            MarkValue = 37.0,
                            StudentID = 2017876764
                        },
                        new
                        {
                            MarkID = 19,
                            AssessmentID = 519,
                            MarkType = 1,
                            MarkValue = 54.0,
                            StudentID = 2017876764
                        },
                        new
                        {
                            MarkID = 20,
                            AssessmentID = 520,
                            MarkType = 1,
                            MarkValue = 76.0,
                            StudentID = 2017876764
                        },
                        new
                        {
                            MarkID = 21,
                            AssessmentID = 521,
                            MarkType = 1,
                            MarkValue = 66.0,
                            StudentID = 2017876764
                        },
                        new
                        {
                            MarkID = 22,
                            AssessmentID = 501,
                            MarkType = 1,
                            MarkValue = 56.0,
                            StudentID = 2016875761
                        },
                        new
                        {
                            MarkID = 23,
                            AssessmentID = 502,
                            MarkType = 1,
                            MarkValue = 33.0,
                            StudentID = 2016875761
                        },
                        new
                        {
                            MarkID = 24,
                            AssessmentID = 503,
                            MarkType = 1,
                            MarkValue = 96.0,
                            StudentID = 2016875761
                        },
                        new
                        {
                            MarkID = 25,
                            AssessmentID = 504,
                            MarkType = 1,
                            MarkValue = 18.0,
                            StudentID = 2016875761
                        },
                        new
                        {
                            MarkID = 26,
                            AssessmentID = 505,
                            MarkType = 1,
                            MarkValue = 56.0,
                            StudentID = 2016875761
                        },
                        new
                        {
                            MarkID = 27,
                            AssessmentID = 506,
                            MarkType = 1,
                            MarkValue = 41.0,
                            StudentID = 2016875761
                        },
                        new
                        {
                            MarkID = 28,
                            AssessmentID = 507,
                            MarkType = 1,
                            MarkValue = 88.0,
                            StudentID = 2016875761
                        },
                        new
                        {
                            MarkID = 29,
                            AssessmentID = 508,
                            MarkType = 1,
                            MarkValue = 30.0,
                            StudentID = 2016875761
                        },
                        new
                        {
                            MarkID = 30,
                            AssessmentID = 509,
                            MarkType = 1,
                            MarkValue = 98.0,
                            StudentID = 2016875761
                        },
                        new
                        {
                            MarkID = 31,
                            AssessmentID = 510,
                            MarkType = 1,
                            MarkValue = 55.0,
                            StudentID = 2016875761
                        },
                        new
                        {
                            MarkID = 32,
                            AssessmentID = 511,
                            MarkType = 1,
                            MarkValue = 94.0,
                            StudentID = 2016875761
                        },
                        new
                        {
                            MarkID = 33,
                            AssessmentID = 512,
                            MarkType = 1,
                            MarkValue = 47.0,
                            StudentID = 2016875761
                        },
                        new
                        {
                            MarkID = 34,
                            AssessmentID = 513,
                            MarkType = 1,
                            MarkValue = 88.0,
                            StudentID = 2016875761
                        },
                        new
                        {
                            MarkID = 35,
                            AssessmentID = 514,
                            MarkType = 1,
                            MarkValue = 39.0,
                            StudentID = 2016875761
                        },
                        new
                        {
                            MarkID = 36,
                            AssessmentID = 515,
                            MarkType = 1,
                            MarkValue = 92.0,
                            StudentID = 2016875761
                        },
                        new
                        {
                            MarkID = 37,
                            AssessmentID = 516,
                            MarkType = 1,
                            MarkValue = 55.0,
                            StudentID = 2016875761
                        },
                        new
                        {
                            MarkID = 38,
                            AssessmentID = 517,
                            MarkType = 1,
                            MarkValue = 41.0,
                            StudentID = 2016875761
                        },
                        new
                        {
                            MarkID = 39,
                            AssessmentID = 518,
                            MarkType = 1,
                            MarkValue = 67.0,
                            StudentID = 2016875761
                        },
                        new
                        {
                            MarkID = 40,
                            AssessmentID = 519,
                            MarkType = 1,
                            MarkValue = 84.0,
                            StudentID = 2016875761
                        },
                        new
                        {
                            MarkID = 41,
                            AssessmentID = 520,
                            MarkType = 1,
                            MarkValue = 36.0,
                            StudentID = 2016875761
                        },
                        new
                        {
                            MarkID = 42,
                            AssessmentID = 521,
                            MarkType = 1,
                            MarkValue = 96.0,
                            StudentID = 2016875761
                        });
                });

            modelBuilder.Entity("TimeTable.Models.Entities.Module", b =>
                {
                    b.Property<int>("ModuleID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseID");

                    b.Property<string>("ModuleDescription");

                    b.Property<string>("ModuleName");

                    b.HasKey("ModuleID");

                    b.HasIndex("CourseID");

                    b.ToTable("Module");

                    b.HasData(
                        new
                        {
                            ModuleID = 401,
                            CourseID = 201,
                            ModuleDescription = "Networking",
                            ModuleName = "CSIS3744"
                        },
                        new
                        {
                            ModuleID = 402,
                            CourseID = 201,
                            ModuleDescription = "Introduction to Software Engineering",
                            ModuleName = "CSIS3724"
                        },
                        new
                        {
                            ModuleID = 403,
                            CourseID = 201,
                            ModuleDescription = "Internet Programming",
                            ModuleName = "CSIS3714"
                        },
                        new
                        {
                            ModuleID = 404,
                            CourseID = 201,
                            ModuleDescription = "Introduction to Databases",
                            ModuleName = "CSIS3734"
                        });
                });

            modelBuilder.Entity("TimeTable.Models.Entities.ModuleAssessment", b =>
                {
                    b.Property<int>("ModuleAssessmentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssessmentID");

                    b.Property<int>("ModuleID");

                    b.HasKey("ModuleAssessmentID");

                    b.ToTable("ModuleAssessments");

                    b.HasData(
                        new
                        {
                            ModuleAssessmentID = 1,
                            AssessmentID = 500,
                            ModuleID = 403
                        },
                        new
                        {
                            ModuleAssessmentID = 2,
                            AssessmentID = 501,
                            ModuleID = 403
                        },
                        new
                        {
                            ModuleAssessmentID = 3,
                            AssessmentID = 502,
                            ModuleID = 403
                        },
                        new
                        {
                            ModuleAssessmentID = 4,
                            AssessmentID = 503,
                            ModuleID = 403
                        },
                        new
                        {
                            ModuleAssessmentID = 5,
                            AssessmentID = 504,
                            ModuleID = 403
                        },
                        new
                        {
                            ModuleAssessmentID = 6,
                            AssessmentID = 505,
                            ModuleID = 403
                        },
                        new
                        {
                            ModuleAssessmentID = 7,
                            AssessmentID = 506,
                            ModuleID = 401
                        },
                        new
                        {
                            ModuleAssessmentID = 8,
                            AssessmentID = 507,
                            ModuleID = 401
                        },
                        new
                        {
                            ModuleAssessmentID = 9,
                            AssessmentID = 508,
                            ModuleID = 401
                        },
                        new
                        {
                            ModuleAssessmentID = 10,
                            AssessmentID = 509,
                            ModuleID = 401
                        },
                        new
                        {
                            ModuleAssessmentID = 11,
                            AssessmentID = 510,
                            ModuleID = 401
                        },
                        new
                        {
                            ModuleAssessmentID = 12,
                            AssessmentID = 511,
                            ModuleID = 402
                        },
                        new
                        {
                            ModuleAssessmentID = 13,
                            AssessmentID = 512,
                            ModuleID = 402
                        },
                        new
                        {
                            ModuleAssessmentID = 14,
                            AssessmentID = 513,
                            ModuleID = 402
                        },
                        new
                        {
                            ModuleAssessmentID = 15,
                            AssessmentID = 514,
                            ModuleID = 402
                        },
                        new
                        {
                            ModuleAssessmentID = 16,
                            AssessmentID = 515,
                            ModuleID = 402
                        },
                        new
                        {
                            ModuleAssessmentID = 17,
                            AssessmentID = 516,
                            ModuleID = 404
                        },
                        new
                        {
                            ModuleAssessmentID = 18,
                            AssessmentID = 517,
                            ModuleID = 404
                        },
                        new
                        {
                            ModuleAssessmentID = 19,
                            AssessmentID = 518,
                            ModuleID = 404
                        },
                        new
                        {
                            ModuleAssessmentID = 20,
                            AssessmentID = 519,
                            ModuleID = 404
                        },
                        new
                        {
                            ModuleAssessmentID = 21,
                            AssessmentID = 520,
                            ModuleID = 404
                        },
                        new
                        {
                            ModuleAssessmentID = 22,
                            AssessmentID = 521,
                            ModuleID = 404
                        });
                });

            modelBuilder.Entity("TimeTable.Models.Entities.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseID");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("StudentID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 2017876764,
                            CourseID = "201",
                            FirstName = "Alexander",
                            LastName = "Carson"
                        },
                        new
                        {
                            StudentID = 2016875761,
                            CourseID = "201",
                            FirstName = "Meredith",
                            LastName = "Alonso"
                        },
                        new
                        {
                            StudentID = 2018867690,
                            CourseID = "201",
                            FirstName = "Nino",
                            LastName = "Anand"
                        },
                        new
                        {
                            StudentID = 2016039762,
                            CourseID = "201",
                            FirstName = "Norman",
                            LastName = "Gytis"
                        },
                        new
                        {
                            StudentID = 2017106766,
                            CourseID = "201",
                            FirstName = "Meluthi",
                            LastName = "Magwenya"
                        },
                        new
                        {
                            StudentID = 2017106778,
                            CourseID = "201",
                            FirstName = "Michael",
                            LastName = "Schmidt"
                        });
                });

            modelBuilder.Entity("TimeTable.Models.Entities.Venue", b =>
                {
                    b.Property<int>("VenueID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("VenueName");

                    b.Property<string>("VenueRoom");

                    b.HasKey("VenueID");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            VenueID = 301,
                            VenueName = "FGG",
                            VenueRoom = "255"
                        },
                        new
                        {
                            VenueID = 302,
                            VenueName = "FGG",
                            VenueRoom = "378"
                        },
                        new
                        {
                            VenueID = 303,
                            VenueName = "HMS",
                            VenueRoom = "--"
                        },
                        new
                        {
                            VenueID = 304,
                            VenueName = "LANDBOU",
                            VenueRoom = "5"
                        },
                        new
                        {
                            VenueID = 305,
                            VenueName = "EBW",
                            VenueRoom = "7"
                        });
                });

            modelBuilder.Entity("TimeTable.Models.Entities.Assessment", b =>
                {
                    b.HasOne("TimeTable.Models.Entities.Module")
                        .WithMany("Assessments")
                        .HasForeignKey("ModuleID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TimeTable.Models.Entities.Module", b =>
                {
                    b.HasOne("TimeTable.Models.Entities.Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
